"""Vault configuration — discovery, parsing, path resolution."""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None  # type: ignore[assignment]

try:
    import toml as _toml  # fallback for TOML writing
except ModuleNotFoundError:
    _toml = None  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Config model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class VaultSection:
    name: str = "My Wiki"
    language: str = "en"
    source_dir: str = "sources"
    wiki_dir: str = "wiki"
    pages_subdir: str = "pages"


@dataclass(frozen=True)
class DB9Section:
    url: str = ""


@dataclass(frozen=True)
class WikiConfig:
    vault: VaultSection = field(default_factory=VaultSection)
    db9: DB9Section | None = None


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CONFIG_PATH = ".llm-wiki/config.toml"

DEFAULT_CONFIG = WikiConfig()

TEMPLATE_PURPOSE = """\
---
title: Wiki Purpose
---

# Purpose

Describe what this wiki is about, its scope, and intended audience.

Example: "This wiki tracks my research on distributed systems, covering papers, concepts, and open questions."
"""

TEMPLATE_SCHEMA = """\
---
title: Wiki Schema
---

# Schema

This file defines the wiki's page conventions, frontmatter rules, and naming standards.
Edit it to match your domain. The defaults below follow the
[Karpathy LLM Wiki](https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f) pattern.

## Page Types

| Type | Description | Examples |
|:---|:---|:---|
| **Concept** | A single idea, pattern, or principle | `distributed-consensus.md`, `eventual-consistency.md` |
| **Entity** | A system, tool, or technology | `apache-kafka.md`, `postgresql.md` |
| **Synthesis** | Cross-page analysis (auto-generated by /query) | `consensus-tradeoffs.md` |
| **Source** | Summary of an ingested document | `ddia-chapter-5.md` |

## Naming Convention

- **kebab-case** for all filenames: `distributed-consensus.md`
- **Single topic per page** — if a section grows too large, split into its own page
- **Subdirectories optional** — use when wiki exceeds ~50 pages: `wiki/pages/concepts/`, `wiki/pages/entities/`

## Required Frontmatter

Every wiki page must include:

```yaml
---
title: Page Title
description: One-line summary of the page
tags: []
sources: []
created: YYYY-MM-DD
updated: YYYY-MM-DD
---
```

### Frontmatter Fields

| Field | Required | Description |
|:---|:---:|:---|
| `title` | Yes | Page title (must match `# Heading`) |
| `description` | Yes | One-line summary (used in index.md and search) |
| `tags` | Yes | Category tags from taxonomy below |
| `sources` | Yes | Paths to source files (relative to `sources/`) |
| `aliases` | No | Alternate names, abbreviations, translations (improves wikilink matching) |
| `status` | conditional | Required for issue/bug pages: `open` / `resolved` / `wontfix` |
| `created` | Yes | Creation date |
| `updated` | Yes | Last update date |

## Wikilinks

Use `[[page-name]]` for every entity that has (or should have) its own page.
Linked pages that don't exist yet become "wanted pages" — a useful signal for what to write next.

GOOD: "Apache Doris uses [[raft-consensus]] for replication"
BAD:  "Apache Doris uses Raft for replication" (no wikilink, loses the connection)

## Related Section

Every page should end with a `## Related` section:

```markdown
## Related

- [[other-page]] — one-line relationship description
- [[another-page]] — how it relates
```

## Tags

Define your tag taxonomy here as the wiki grows. Start minimal, expand as needed.

Example:
- `concept` — abstract ideas and patterns
- `system` — concrete tools and technologies
- `method` — processes and workflows
- `synthesis` — cross-page analysis (auto-generated)
"""

TEMPLATE_AGENT = """\
---
title: Wiki Agent
---

# Wiki Agent

This page defines the agent's role, behavior, and operating rules for this wiki vault.
The AI agent reads this file (via the philip wiki skill) on every wiki operation.

## Identity

Describe the agent's role here. Example:

> I am the knowledge maintainer for [project name]. I observe discussions,
> extract valuable information, and organize it into structured wiki pages.

## Responsibilities

- Continuously ingest wiki-worthy information from received inputs
- Maintain accuracy and freshness of existing wiki pages
- Cross-reference related topics with [[wikilinks]]
- Never participate in discussions — observe and record only

## Ingest Rules

### MUST capture
- Decisions and their rationale
- Architecture and design conclusions
- Task/issue lifecycle events (created, assigned, completed)
- Bug reports and resolutions
- New systems, concepts, or processes

### MAY capture
- Unconfirmed proposals and ideas
- Tool and workflow discussions
- Performance observations

### NEVER capture
- Casual conversation and greetings
- Credentials, tokens, personal data
- Information already recorded in the wiki
- Emoji-only or single-word reactions

## Output Standards

- Write in the language specified in `.llm-wiki/config.toml`
- Each wiki page focuses on one topic
- Always include source attribution
- Use [[wikilinks]] for every entity that has or should have a page
- Append every action to wiki-log.md
- After every operation, run `philip wiki sync`

## Layout

- `wiki/pages/` — AI-maintained wiki pages (Obsidian-compatible)
- `wiki/wiki-agent.md` — This file (agent behavioral rules)
- `wiki/wiki-purpose.md` — Purpose and scope
- `wiki/wiki-schema.md` — Page naming conventions
- `wiki/wiki-log.md` — Append-only operation log
- `sources/` — Raw source documents, date-partitioned (immutable)
- `.llm-wiki/` — Config and sync state

## CLI

- `philip wiki search <query>` — BM25 (+ vector, if DB9 configured) keyword search
- `philip wiki graph` — communities, hubs, orphans, wanted pages
- `philip wiki status` — stats + health summary
- `philip wiki sync` — track mtime/SHA256, push embeddings to DB9 if configured

## Rules

1. Always read `wiki/wiki-purpose.md` and `wiki/wiki-schema.md` before any operation
2. Never modify files in `sources/` — they are immutable raw inputs
3. Use `[[wikilinks]` for cross-references between wiki pages
4. After every operation, append an entry to `wiki/wiki-log.md` **and** run `philip wiki sync`
5. When you receive information, apply your auto-ingest criteria — do not wait for explicit commands
"""

TEMPLATE_CONFIG = """\
[vault]
name = "My Wiki"
language = "en"
# source_dir = "sources"  # Optional: customize input directory (default: "sources")
# wiki_dir = "wiki"       # Optional: customize wiki root directory (default: "wiki")
# pages_subdir = "pages"  # Optional: store wiki pages in wiki/pages/ (default: "pages")

# [db9]
# url = "your-db9-connection-string"
"""

TEMPLATE_LOG = """\
# Change Log

Format: `YYYY-MM-DD HH:MM | operation | details`

"""


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def find_vault_root(from_path: str | Path = ".") -> Path | None:
    """Walk up *from_path* looking for ``.llm-wiki/config.toml``."""
    d = Path(from_path).resolve()
    while True:
        if (d / CONFIG_PATH).exists():
            return d
        parent = d.parent
        if parent == d:
            return None
        d = parent


def require_vault_root(from_path: str | Path = ".") -> Path:
    """Like :func:`find_vault_root` but raises on failure."""
    root = find_vault_root(from_path)
    if root is None:
        raise SystemExit(
            "Error: Not inside an llm-wiki vault. Run `philip wiki init` first."
        )
    return root


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def _parse_toml(text: str) -> dict[str, Any]:
    """Parse TOML text, trying tomllib first, then toml fallback."""
    if tomllib is not None:
        return tomllib.loads(text)  # type: ignore[union-attr]
    if _toml is not None:
        return _toml.loads(text)  # type: ignore[union-attr]
    raise RuntimeError("No TOML parser available. Install `toml` or use Python 3.11+.")


def load_config(vault_root: str | Path) -> WikiConfig:
    """Load ``.llm-wiki/config.toml`` with defaults."""
    config_path = Path(vault_root) / CONFIG_PATH
    if not config_path.exists():
        return DEFAULT_CONFIG
    raw = config_path.read_text(encoding="utf-8")
    data = _parse_toml(raw)

    vault_raw = data.get("vault", {})
    vault = VaultSection(
        name=vault_raw.get("name", "My Wiki"),
        language=vault_raw.get("language", "en"),
        source_dir=vault_raw.get("source_dir", "sources"),
        wiki_dir=vault_raw.get("wiki_dir", "wiki"),
        pages_subdir=vault_raw.get("pages_subdir", "pages"),
    )

    db9_raw = data.get("db9")
    db9 = DB9Section(url=db9_raw["url"]) if db9_raw and db9_raw.get("url") else None

    return WikiConfig(vault=vault, db9=db9)


# ---------------------------------------------------------------------------
# Path computation
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class VaultPaths:
    wiki: Path          # wiki/pages/ (or wiki/ if pages_subdir is empty)
    wiki_root: Path     # wiki/
    sources: Path       # sources/
    purpose: Path       # wiki/wiki-purpose.md
    schema: Path        # wiki/wiki-schema.md
    agent: Path         # wiki/wiki-agent.md
    log: Path           # wiki/wiki-log.md
    claude_md: Path     # CLAUDE.md
    agents_md: Path     # AGENTS.md
    claude_skills_dir: Path  # .claude/skills/
    agents_skills_dir: Path  # .agents/skills/
    config: Path        # .llm-wiki/config.toml
    sync_state: Path    # .llm-wiki/sync-state.json
    llm_wiki_dir: Path  # .llm-wiki/


def vault_paths(root: str | Path, config: WikiConfig | None = None) -> VaultPaths:
    """Compute all canonical vault paths from root + config."""
    root = Path(root)
    cfg = config or DEFAULT_CONFIG
    source_dir = cfg.vault.source_dir or "sources"
    wiki_dir = cfg.vault.wiki_dir or "wiki"
    pages_subdir = cfg.vault.pages_subdir

    wiki_root = root / wiki_dir
    wiki_pages = wiki_root / pages_subdir if pages_subdir else wiki_root

    return VaultPaths(
        wiki=wiki_pages,
        wiki_root=wiki_root,
        sources=root / source_dir,
        purpose=wiki_root / "wiki-purpose.md",
        schema=wiki_root / "wiki-schema.md",
        agent=wiki_root / "wiki-agent.md",
        log=wiki_root / "wiki-log.md",
        claude_md=root / "CLAUDE.md",
        agents_md=root / "AGENTS.md",
        claude_skills_dir=root / ".claude" / "skills",
        agents_skills_dir=root / ".agents" / "skills",
        config=root / CONFIG_PATH,
        sync_state=root / ".llm-wiki" / "sync-state.json",
        llm_wiki_dir=root / ".llm-wiki",
    )
